fos_user_security:

    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


#fos_user_profile:
#
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#
#    prefix: /profile
#
#
#fos_user_register:
#
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#
#    prefix: /register
#
#
#fos_user_resetting:
#
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#
#    prefix: /resetting
#
#
#fos_user_change_password:
#
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#
#    prefix: /profile
#
#
#caftan_user:
#    resource: "@CAFTANUserBundle/Resources/config/routing.yml"
#    prefix:   /

caftan_admin:
    resource: "@CAFTANAdminBundle/Resources/config/routing.yml"
    prefix:   /

caftan_app:
    resource: "@CAFTANAppBundle/Resources/config/routing.yml"
    prefix:   /

#login:
#    path: /login
#    defaults:
#        _controller: CAFTANAppBundle:Connexion:login
#
#login_check:
#    path: /login_check
#
#logout:
#    path: /logout
