<?php

namespace CAFTAN\AppBundle\Repository;


use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository {
       

    public function getAdverts($page, $nbPerPage) {


        $queryBuilder = $this->createQueryBuilder('a');

        $query = $queryBuilder->getQuery();




        $query

                // On définit l'annonce à partir de laquelle commencer la liste
                ->setFirstResult(($page - 1) * $nbPerPage)

                // Ainsi que le nombre d'annonce à afficher sur une page
                ->setMaxResults($nbPerPage)

        ;


        // Enfin, on retourne l'objet Paginator correspondant à la requête construite
        // (n'oubliez pas le use correspondant en début de fichier)

        return new Paginator($query, true);
    }

    public function getmyAdverts($page, $id, $nbPerPage) {


        $queryBuilder = $this->createQueryBuilder('a')
                ->where('a.annonceur = :id')
                ->setParameter('id', $id);

        $query = $queryBuilder->getQuery();




        $query

                // On définit l'annonce à partir de laquelle commencer la liste
                ->setFirstResult(($page - 1) * $nbPerPage)

                // Ainsi que le nombre d'annonce à afficher sur une page
                ->setMaxResults($nbPerPage)

        ;


        // Enfin, on retourne l'objet Paginator correspondant à la requête construite
        // (n'oubliez pas le use correspondant en début de fichier)

        return new Paginator($query, true);
    }
   public function findBySearch($search){
//        $qb = $this->createQueryBuilder('a');
//            $qb ->where('a.neuf = :neuf')
//                    ->setParameter('neuf', $search->getNeuf())
//                ->andWhere('a.prix >= :prixmin')
//                    ->setParameter('prixmin', $search->getPrixmin())
//                ->andWhere('a.prix <= :prixmax')
//                    ->setParameter('prixmax', $search->getPrixmax())
//                ->andWhere('a.annonceur.adress.cp = :cp')
//                    ->setParameter('cp', $search->getCp())
//
//        ;
       
            $qb = $this
                ->createQueryBuilder('a')
                ->leftJoin('a.annonceur', 'ann')
                ->addSelect('ann')
                ->leftJoin('ann.adress', 'ad')
                ->addSelect('ad')
                ->where('ad.cp = :cp')
                ->setParameter('cp', $search->getCp())
                ->andwhere('a.neuf = :neuf')
                ->setParameter('neuf', $search->getNeuf())
                ->andWhere('a.prix >= :prixmin')
                ->setParameter('prixmin', $search->getPrixmin())
                ->andWhere('a.prix <= :prixmax')
                ->setParameter('prixmax', $search->getPrixmax())


        ;
        return $qb
                        ->getQuery()
                        ->getResult()

        ;
    }

   

}
