<?php

namespace CAFTAN\AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommentWithUser()

{

  $qb = $this

    ->createQueryBuilder('c')

    ->leftJoin('c.commenter', 'u')

    ->addSelect('u')

  ;


  return $qb

    ->getQuery()

    ->getResult()

  ;

}
}
