<?php

namespace CAFTAN\AppBundle\Repository;

/**
 * InfosdiversRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfosdiversRepository extends \Doctrine\ORM\EntityRepository
{
}
